### ISSUE TITLE
Please consider moving it under Processing

### ISSUE THREAD

**Issue by pcav** [klausib/event_layer#3]
You'll save coding the interface, and the user will be able to integrate this into more complex workflows, having iterations, and much more.
Ask @volaya for howto, or have a look to other Processing plugins.

**Comment by klausib** [comment]
I cant follow You. What should be done and why? If the Sourcepole Plugin doesnt meet the necessary conditions (after 5 years) to stay in the official Plugin repository by now, no problem, just delete it from there.

**Comment by pcav** [comment]
This is a suggestion to improve your plugin, not a hard requirement (hence the word "consider" in the title).
This would bring a number of important advantages, both for the user and for the developer (no need to design a GUI).

**Comment by klausib** [comment]
Yes, I know and thank you for your effort. The EventLayer Plugin has to fullfill internal needs. Our employees are used to it like it is, so I am not allowed to change it that way. Its not obligatory necessary to keep it public anyway.
